name: Build
on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: build binary
        run: make build
